নামপাই কি?

পাইথনে নিউমেরিক্যাল ক্যালকুলেশনের  জন্য দারুণ একটি প্যাকেজ হচ্ছে NumPy। যার পূর্ণরুপ হচ্ছে Numarical Python।  নামপাইতে লিনিয়ার অ্যালজেব্রা, ফুরিয়ার ট্রান্সফরমেশন, মেট্রিক্স সহ অন্যান্য গাণিতিক ফাংশন গুলো রয়েছে। NumPy নিয়ে কাজ করাও দারুণ সহজ। বর্তমানে বেশির ভাগ মেশিন লার্নিং লাইব্রেরীতে নামপাই ব্যবহৃত হয়েছে।

পাইথনে বিল্টইন অ্যারে নেই। লিস্ট দিয়ে যদিও অ্যারের কাজ করা যায়, তবে অ্যারে থেকে স্লো। নামপাই ব্যবহার করে পাইথনে অ্যারে নিয়ে কাজ করা যায়। যা লিস্ট থেকে প্রায় ৫০ গুণ দ্রুত কাজ করে। নামপাই অ্যারে অবজেক্টকে বলে ndarray। ডেটা সাইন্স, মেশিন লার্নিং এর ক্ষেত্রে বেশির ভাগ সময় অ্যারে নিয়ে কাজ করতে হয়। আর যেখানে স্পিড একটা গুরুত্বপূর্ণ ফ্যাক্টর হিসেবে কাজ করে। নামপাই অ্যারে সি অ্যারের মত। যেখানে ডেটা গুলো কম্পিউটার মেমরিতে সিরিয়ালি রাখা হয়।  যার কারণে দ্রুততার সাথে ডেটা এক্সেস এবং কম্পিউট করা যায়। এমনকি নামপাই এর বেশির ভাগ অংশ সি প্রোগ্রামিং এ লেখা।

কি ভাবে কম্পিউটারে নামপাই ইন্সটল করব? 

পাইথনে নামপাই প্যাকেজ দেওয়া থাকে না। নামপাই ব্যবহার করতে হলে প্রথমে ইন্সটল করে নিতে হবে।  অনেক ভাবেই ইন্সটল করা যায়। সবচেয়ে সহজ উপায় হচ্ছে pip ব্যবহার করে ইন্সটলঃ

1
pip install numpy
NumPy ইন্সটল করার পরের কাজ হচ্ছে আমাদের প্রজেক্টে NumPy ইম্পোর্ট করা। তা সহজ। তার জন্য লিখতে হবেঃ

1
import numpy as np
এবার আমরা NumPy ব্যবহার করে ডেটা এনালাইসিস শুরু করতে পারি। যেমন কয়েকটি নাম্বারের mean, median and Standard Deviation বের করতে পারি নিচের মত করেঃ

In [402]:
	
import numpy as np

In [403]:
# এবার আমরা NumPy ব্যবহার করে ডেটা 
# এনালাইসিস শুরু করতে পারি। যেমন কয়েকটি নাম্বারের 
# mean, median and Standard Deviation
# বের করতে পারি নিচের মত করেঃ

import numpy as np  
numbers = [1,2,3,4,5]
meanvalue = np.mean(numbers)
medianvalue = np.median(numbers)
stddeviation = np.std(numbers)
print("Mean:", meanvalue)
print("Median:", medianvalue)
print("Standard Deviation:", stddeviation)

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951


In [404]:
 	
import numpy as np
numbers = [1,2,3,4,5]
print (np.mean(numbers) )
print (np.median(numbers))
print (np.std(numbers))

3.0
3.0
1.4142135623730951


In [405]:

# NumPy দিয়ে কিভাবে array তৈরি করা যায়
import numpy as np
numbers = [1,2,3,4,5]
# create numpy array using list
np_array = np.array(numbers)
print(np_array)
# print type of the array
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


এখানে যখন অ্যারের টাইপ দেখেছি, আউটপুট পেয়েছি ndarray, যা নামপাই অ্যারের ডেটা টাইপ।

নামপাই ব্যবহার করে র‍্যান্ডম নাম্বার তৈরি

অনেক সময় আমাদের কিছু ডামি ডেটা জেনারেট করতে হয়। নামপাই দিয়ে সহজেই করা যায়। যেমনঃ

In [406]:
import numpy as np
# creating an array of 10 zeros
zeros = np.zeros(10)
print("Total number of Zeros: ", zeros)
print(type(zeros))

Total number of Zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


## 1 দিয়ে পূর্ণ একটা অ্যারে তৈরিঃ

In [407]:
# 1 দিয়ে পূর্ণ একটা অ্যারে তৈরিঃ
import numpy as np
ones = np.ones(5)
print("Total number of Ones: ", ones)  
print(type(ones)) 

Total number of Ones:  [1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


নির্দিষ্ট রেঞ্জের অ্যারে তৈরিঃ

In [408]:
 
import numpy as np
# creating an array with 1-9 numbers
numbers = np.arange(10)
print("Total Number of Range : ", numbers)


Total Number of Range :  [0 1 2 3 4 5 6 7 8 9]


র‍্যান্ডম অ্যারে তৈরিঃ

In [409]:
 
import numpy as np
# generating random array
rand = np.random.rand(5)
print("Random array: ", rand)
print(type(rand))


Random array:  [0.14290527 0.95416767 0.92400182 0.26566143 0.12450698]
<class 'numpy.ndarray'>


In [410]:
 
import numpy as np
# generating random array
rand = np.random.rand(5)
print("Random array: ", rand)
print(type(rand))

Random array:  [0.00412955 0.23479839 0.41624437 0.82956324 0.8750729 ]
<class 'numpy.ndarray'>


In [411]:
 
import numpy as np
# generating random array
rand = np.random.rand(5)
print("Random array: ", rand)
print(type(rand))

Random array:  [0.00785895 0.44560759 0.93658826 0.54683995 0.72989309]
<class 'numpy.ndarray'>


শূন্য অ্যারে তৈরিঃ

In [412]:
# শূন্য অ্যারে তৈরিঃ

 
import numpy as np
# creating empty array
empty = np.empty(10)
 
print("Empty array: ", empty)


Empty array:  [0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323 3.0e-323 3.5e-323
 4.0e-323 4.4e-323]


In [413]:
import numpy as np
# creating empty array
empty_array = np.empty(10)
print("Empty array: ", empty_array)
print(type(empty_array))    

Empty array:  [0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323 3.0e-323 3.5e-323
 4.0e-323 4.4e-323]
<class 'numpy.ndarray'>


এই কোডটি NumPy লাইব্রেরি ব্যবহার করে একটি খালি অ্যারে তৈরি করে।
np.empty(10) দ্বারা ১০টি উপাদান বিশিষ্ট একটি অ্যারে তৈরি হয়,
 তবে এতে কোনো মান ইনিশিয়ালাইজ করা হয় না।
ফলে অ্যারেতে মেমরির আগের র‍্যান্ডম বা গারবেজ মানগুলো দেখা যায়।
print("Empty array:", empty_array) লাইনটি অ্যারেটি স্ক্রিনে প্রদর্শন করে।
print(type(empty_array)) লাইনটি অ্যারেটির টাইপ দেখায়, যা <class 'numpy.ndarray'>।
অর্থাৎ এটি একটি NumPy অ্যারে, 
যা দ্রুত অ্যারে তৈরির জন্য ব্যবহৃত হয় কিন্তু মান নির্দিষ্ট করে না।

কাস্টম একটা অ্যারে তৈরিঃ  
 এর মানে 0-100 এর মধ্যে সংখ্যা গুলো ব্যবহার করে একটা অ্যারে তৈরি করতে। যেখানে প্রতি ধাপে ৫টা সংখ্যা বাদ দিয়ে পরের সংখ্যা নিতে। আউটপুট পাবো এমনঃ

In [414]:
import numpy as np
# creating custom array
lst = np.arange(0, 100, 5)
print("Custom array: ", lst)

Custom array:  [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


একটা নির্দিষ্ট নাম্বার ব্যবহার করে অ্যারে ফিল করাঃ

 
এর মানে হচ্ছে ১০টা আইটেমের একটা অ্যারে নিতে যা 4 সংখ্যা দিয়ে পূরণ করবে।  

 
 

In [415]:
import numpy as np
fours = np.full(10, 4)
print(fours)

[4 4 4 4 4 4 4 4 4 4]


একটা নির্দিষ্ট নাম্বার ব্যবহার করে অ্যারে ফিল করাঃ

 
এর মানে হচ্ছে 20 টা আইটেমের একটা অ্যারে নিতে যা 10 সংখ্যা দিয়ে পূরণ করবে।  

 
 

In [416]:
import numpy as np
ten= np.full(20, 10)
print(ten)

[10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10]


In [417]:
import numpy as np
list_numbers= [1,2,3,4,5]
numpy_array_numbers= np.array(numbers)
print(numpy_array_numbers)
print(type(numpy_array_numbers))
 


[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


উপরে যে অ্যারে গুলো তৈরি করেছি, সেগুলো ছিল সিঙ্গেল ডাইমেনশন। আমরা চাইলে মাল্টি ডাইমেনশন অ্যারে তৈরি করতে পারিঃ
2D অ্যারে তৈরিঃ
যেমন 2D অ্যারে এভাবে তৈরি করতে পারিঃ

In [418]:
 
import numpy as np
two_d = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]])
 
print(two_d)
print(type(two_d))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [419]:
 
import numpy as np
two_d = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
 
print(two_d)
print(type(two_d))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [420]:
 
import numpy as np
two_d = np.array( [   [1, 2, 3, 4]   ,   [5, 6, 7, 8]   ] )
  
print(two_d)
print(type(two_d))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [421]:
 
import numpy as np
two_d = np.array( [   [1, 2, 3, 4]  
                    ,   [5, 6, 7, 8]   ] )
  
print(two_d)
print(type(two_d))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [422]:
 
import numpy as np
two_d = np.array( [[1, 2, 3, 4] ,
                   [5, 6, 7, 8]] )
   
print(two_d)
print(type(two_d))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


2D র‍্যান্ডম অ্যারে এভাবে তৈরি করতে পারিঃ

যা আমাদের 5*5 একটা র‍্যান্ডম অ্যারে তৈরি করে দিবে। আর আউটপুট দিবে এমনঃ

In [423]:
 
import numpy as np
two_d_random = np.random.rand(5, 5)
print(two_d_random)
print(type(two_d_random))


[[0.33904769 0.48177592 0.78284955 0.31604055 0.75587565]
 [0.13405996 0.34257843 0.49721378 0.07051941 0.0398948 ]
 [0.52487016 0.13601355 0.89167555 0.66601198 0.31027731]
 [0.37043354 0.57009297 0.7783197  0.24413801 0.70828728]
 [0.53868746 0.15052058 0.81876374 0.50348553 0.33956486]]
<class 'numpy.ndarray'>


In [424]:
 
import numpy as np
two_d_random = np.random.rand(4, 4)
print(two_d_random)
print(type(two_d_random))   

[[0.64514936 0.47256105 0.02048599 0.51946758]
 [0.3737177  0.56439143 0.20799758 0.1765162 ]
 [0.08212935 0.80577069 0.23145809 0.68547141]
 [0.17434987 0.95036281 0.3204086  0.6256291 ]]
<class 'numpy.ndarray'>


In [425]:
 
import numpy as np
two_d_random = np.random.rand(2, 2)
print(two_d_random)
print(type(two_d_random))   

[[0.5295484  0.04870839]
 [0.1182022  0.07510904]]
<class 'numpy.ndarray'>


In [426]:
 
import numpy as np
two_d_random = np.random.rand(2, 4)
print(two_d_random)
print(type(two_d_random))

[[0.49788684 0.65303832 0.0553643  0.46568349]
 [0.0255167  0.55565669 0.34644927 0.08941203]]
<class 'numpy.ndarray'>


In [427]:
import numpy as np
 
numpy_array = np.full((3, 3), 7)
 
print( numpy_array)
print(type(numpy_array))

[[7 7 7]
 [7 7 7]
 [7 7 7]]
<class 'numpy.ndarray'>


In [428]:
import numpy as np
 
numpy_array = np.full((2, 2), 5)
 
print( numpy_array)
print(type(numpy_array))

[[5 5]
 [5 5]]
<class 'numpy.ndarray'>


In [429]:
import numpy as np
 
numpy_array = np.full((2, 1), 5)
 
print( numpy_array)
print(type(numpy_array))

[[5]
 [5]]
<class 'numpy.ndarray'>


In [430]:
import numpy as np
 
numpy_array = np.full((3, 2), 5)
 
print( numpy_array)
print(type(numpy_array))

[[5 5]
 [5 5]
 [5 5]]
<class 'numpy.ndarray'>


In [431]:
import numpy as np
 
numpy_array = np.full((1 , 2), 5)
 
print( numpy_array)
print(type(numpy_array))    

[[5 5]]
<class 'numpy.ndarray'>


Example 1: np.zeros()
 np.zeros((2,3)) 
একটি 2 সারি ও 3 কলামের array তৈরি করে, যেখানে সব মান 0।

In [432]:
import numpy as np
zeros_array = np.zeros((2, 3))
print("Zeros array:\n", zeros_array)
print(type(zeros_array))


Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [433]:
import numpy as np
zeros_array = np.zeros((2, 3))
print("Zeros array:", zeros_array)
print(type(zeros_array))    


Zeros array: [[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


Example 2: np.ones()    .


np.ones((3,2)) একটি 3 সারি ও 2 কলামের array তৈরি করে, যেখানে সব মান 1।

In [434]:
import numpy as np
ones_array = np.ones((3, 2))
print("Ones array:\n", ones_array)
print(type(ones_array))

Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>


Example 3: np.arange() .


np.arange(5, 15, 2) মানে হলো 5 থেকে শুরু করে 15-এর আগে পর্যন্ত সংখ্যা তৈরি করা, প্রতি ধাপে 2 করে বাড়বে।

In [435]:
import numpy as np
range_array = np.arange(5, 15, 2)
print("Arange array:", range_array)
print(type(range_array))


Arange array: [ 5  7  9 11 13]
<class 'numpy.ndarray'>


Bonus Example: np.full()   


np.full((2,3),7) একটি 2x3 ম্যাট্রিক্স তৈরি করে, যার সব ঘরেই মান 7।

In [436]:
import numpy as np
full_array = np.full((2, 3), 7)
print("Full array:\n", full_array)
print(type(full_array))


Full array:
 [[7 7 7]
 [7 7 7]]
<class 'numpy.ndarray'>


3D অ্যারেকে ভাবতে পারেন একের অধিক 2D অ্যারের সমষ্টি। যেমনঃ

 

In [437]:
 
import numpy as np
 
three_d = np.array([[[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]],
 
                   [[13, 14, 15, 16],
                    [17, 18, 19, 20],
                    [21, 22, 23, 24]]])
 
print(three_d)
print(type(three_d))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
<class 'numpy.ndarray'>


এখানে দুইটা 3*4 অ্যারে রয়েছে। 
বুঝতে আরেকটু সহজ হবে যদি আমরা এই অ্যারেটি জেনারেট করিঃ

In [438]:

 
import numpy as np
 
three_d = np.zeros((2, 3, 4))
 
print(three_d)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


প্রথম অ্যারেটাই আমরা 0 দিয়ে তৈরি করেছি। যদি (2, 3, 4) এর পরিবর্তে (4, 3, 4) লিখি, তাহলেঃ

মানে হচ্ছে 4টা 3*4 অ্যারে।
 যখন এমন মাল্টি ডাইমেনশন অ্যারে নিয়ে কাজ করব,
  তখন উল্টা থেকে পড়ব। যেমন (2, 3, 4) কে পড়ব প্রতিটা রোতে ৪টা আইটেম রয়েছে। 
  চারটা আইটেম করে ৩টা কলাম রয়েছে প্রতি স্লাইচে। এবং স্লাইচ রয়েছে ২টা।

In [439]:
import numpy as np
 
three_d = np.zeros((4, 3, 4))
 
print(three_d)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


আমার মত রো এবং কলাম কোনটা, ভুলে গেলে আবার স্মরণ করে নিন। প্রথমে রো, পরে কলাম, পরে স্লাইস। তাহলে (4, 3, 4) এর ক্ষেত্রে হবে প্রতি রোতে ৪টা আইটেম করে মোট ৩টা রো রয়েছে, আর স্লাইস রয়েছে ৪টা! আবার অ্যারেতে কত গুলো আইটেম রয়েছে টোটাল তা এই (4, 3, 4) সংখ্যা গুলো গুণ করলেই পাওয়া যাবে। অর্থাৎ (4, 3, 4) সাইজের অ্যারেতে 48টা আইটেম থাকবে।

এবার একটা 3D অ্যারে র‍্যান্ডম নাম্বার দিয়ে তৈরি করিঃ
 
 

In [440]:
 
import numpy as np
 
three_d = np.random.rand(2, 4, 4)
 
print(three_d)

[[[0.48817705 0.16025559 0.89118714 0.64318757]
  [0.10862037 0.55431884 0.93615191 0.83471469]
  [0.2802281  0.66178555 0.60851911 0.0236524 ]
  [0.74797104 0.58152182 0.12897528 0.19254857]]

 [[0.19233072 0.77659677 0.50772514 0.41023522]
  [0.18564296 0.78431125 0.9734649  0.76239132]
  [0.16079851 0.51241838 0.9052048  0.71259596]
  [0.862276   0.50277136 0.03192903 0.58782335]]]


একই অ্যারে যদি আমরা একটা নির্দিষ্ট সংখ্যা দিয়ে ফিল করতে চাই, তাহলে এভাবে লিখবঃ

  একটা 2*4*4 অ্যারে তৈরি করবে যা ফিল করবে 6 দিয়ে।

In [441]:
 
import numpy as np
three_d = np.full((2, 4, 4), 6)
print(three_d)

[[[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]]
