##  (NUMPY)নামপাই কি?

পাইথনে নিউমেরিক্যাল ক্যালকুলেশনের  জন্য দারুণ একটি প্যাকেজ হচ্ছে NumPy। যার পূর্ণরুপ হচ্ছে Numarical Python।  নামপাইতে লিনিয়ার অ্যালজেব্রা, ফুরিয়ার ট্রান্সফরমেশন, মেট্রিক্স সহ অন্যান্য গাণিতিক ফাংশন গুলো রয়েছে। NumPy নিয়ে কাজ করাও দারুণ সহজ। বর্তমানে বেশির ভাগ মেশিন লার্নিং লাইব্রেরীতে নামপাই ব্যবহৃত হয়েছে।

পাইথনে বিল্টইন অ্যারে নেই। লিস্ট দিয়ে যদিও অ্যারের কাজ করা যায়, তবে অ্যারে থেকে স্লো। নামপাই ব্যবহার করে পাইথনে অ্যারে নিয়ে কাজ করা যায়। যা লিস্ট থেকে প্রায় ৫০ গুণ দ্রুত কাজ করে। নামপাই অ্যারে অবজেক্টকে বলে ndarray। ডেটা সাইন্স, মেশিন লার্নিং এর ক্ষেত্রে বেশির ভাগ সময় অ্যারে নিয়ে কাজ করতে হয়। আর যেখানে স্পিড একটা গুরুত্বপূর্ণ ফ্যাক্টর হিসেবে কাজ করে। নামপাই অ্যারে সি অ্যারের মত। যেখানে ডেটা গুলো কম্পিউটার মেমরিতে সিরিয়ালি রাখা হয়।  যার কারণে 
দ্রুততার সাথে ডেটা এক্সেস এবং কম্পিউট করা যায়। এমনকি নামপাই এর বেশির ভাগ অংশ সি প্রোগ্রামিং এ লেখা।







কি ভাবে কম্পিউটারে নামপাই ইন্সটল করব? 

পাইথনে নামপাই প্যাকেজ দেওয়া থাকে না। নামপাই ব্যবহার করতে হলে প্রথমে ইন্সটল করে নিতে হবে।  অনেক ভাবেই ইন্সটল করা যায়। সবচেয়ে সহজ উপায় হচ্ছে pip ব্যবহার করে ইন্সটলঃ

1
pip install numpy
NumPy ইন্সটল করার পরের কাজ হচ্ছে আমাদের প্রজেক্টে NumPy ইম্পোর্ট করা। তা সহজ। তার জন্য লিখতে হবেঃ

1
import numpy as np
এবার আমরা NumPy ব্যবহার করে ডেটা এনালাইসিস শুরু করতে পারি। যেমন কয়েকটি নাম্বারের mean, median and Standard Deviation বের করতে পারি নিচের মত করেঃ

#  Numpy start  

In [250]:
import numpy as np

In [251]:
# Numerical Python  =   Num +py = numpy

NumPy (Numerical Python) is a powerful Python library for fast numerical and scientific computing.
It provides high-performance multidimensional arrays and mathematical functions.
Widely used in data science and machine learning for efficient computations.

In [252]:
#list
# my_list = [1,2,3,4,5,6,7]   
 
# list contains different data types
# my_list2 = [1,2,3,'four',5.0,6,'  seven']

In [253]:
#array 
# array contain must be of same data type

 

In [254]:
import numpy as np

In [255]:
print(np.__version__)


2.2.6


In [256]:
# create a random integer between 0 and 10
random_int = np.random.randint(0, 10)

print(random_int)

 

6


In [257]:
 
# create a random integer between 0 and 10
x_int = np.random.randint(0, 10)

print(random_int)


6


In [258]:
 
# create a random integer between 0 and 10
random_int = np.random.randint(0, 10)    # 0 to 9 integers   since randint
 
print(random_int)


2


In [259]:
# create a random float number (0 to 1)
import numpy as np

# create a random float number (0 to 1)
random_float = np.random.rand()

print(random_float)


0.09997491581800289


In [260]:
# create a random float number (0 to 1)
import numpy as np

#  create a random float number (0 to 1)
random_float = np.random.rand()

print(random_float)


0.45924889196586716


In [261]:
# create a random float number (0 to 1)
import numpy as np

#  create a random float number (0 to 1)
random_float = np.random.rand()

print(random_float)


0.33370861113902184


In [262]:
# Import the NumPy library
import numpy as np

#   same random number is generated every time)
np.random.seed(42)

# Create a random integer between 0 and 100 (0 inclusive, 100 exclusive)

random_number = np.random.randint(0, 100)
 
print(random_number)


51


In [263]:
# Import the NumPy library
import numpy as np

#  same random number is generated every time)
np.random.seed(42)

# Create a random integer between 0 and 100 (0 inclusive, 100 exclusive)

random_number = np.random.randint(0, 100)
 
print(random_number)


51


In [264]:
# Import the NumPy library
import numpy as np

#  same random number is generated every time)
np.random.seed(42)

# Create a random integer between 0 and 100 (0 inclusive, 100 exclusive)

random_number = np.random.randint(0, 100)
 
print(random_number)

51


In [265]:
import numpy as np

#  create a random integer between 0 and 10
random_int = np.random.randint(0, 10)  

print(random_int)


7


In [266]:
#addition
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

 
add = arr1 + arr2
print("Sum:", add)

 



Sum: [5 7 9]


In [267]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

 
 
subtract = arr1 - arr2
print("Difference:", subtract)

Difference: [-3 -3 -3]


In [268]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
 
multiply = arr1 * arr2
print("Product:", multiply)



Product: [ 4 10 18]


In [269]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

 
divide = arr1 / arr2
print("Division:", divide)

Division: [0.25 0.4  0.5 ]


Matrix Multiplication)

 

In [270]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

 
matrix_multiply = np.dot(arr1, arr2)
print("Matrix Multiplication:\n", matrix_multiply)


Matrix Multiplication:
 [[19 22]
 [43 50]]


In [271]:
import numpy as np

# দুটি ম্যাট্রিক্স তৈরি
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# ম্যাট্রিক্স গুণন
C = np.dot(A, B)

print(C)


[[19 22]
 [43 50]]


In [272]:
arr = np.array([1, 4, 9, 16])

# Square root  function
sqrt_arr = np.sqrt(arr)
print("Square Roots:", sqrt_arr)

 
# exp_arr = np.exp(arr)      # Exponential function
# print("Exponential:", exp_arr)


Square Roots: [1. 2. 3. 4.]


In [273]:
import numpy as np

# 2x3  array of random numbers from a standard normal distribution
random_normal = np.random.randn(2, 3)

print(random_normal)


[[-1.11188012  0.31890218  0.27904129]
 [ 1.01051528 -0.58087813 -0.52516981]]


# Array Indexing

 

In [274]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

#  first element (index 0)
print(arr[0])   

 
print(arr[4])   


10
50


In [352]:
 # last element (index -1)
arr = np.array([10, 20, 30, 40, 50])
print(arr[-1])   

 
print(arr[-2])   


50
40


# Array Slicing

 

In [353]:
# start stop step
arr = np.array([10, 20, 30, 40, 50])

 
print(arr[:3])   # first three elements
 
 
 
 

[10 20 30]


In [354]:
# start stop step
arr = np.array([10, 20, 30, 40, 50])

  
print(arr[1:4])   #
 
 
 


[20 30 40]


In [355]:
# start stop step
arr = np.array([10, 20, 30, 40, 50])

 
 
print(arr[::2])   # start 0 index to end with step 2        10,30,50    because step is 2   so skips one element each time 


[10 30 50]


In [279]:
# শেষ 3 উপাদান
arr = np.array([10, 20, 30, 40, 50])
print(arr[-3:])  # আউটপুট: [30 40 50]

 

[30 40 50]


In [280]:
 # 2য় থেকে 4র্থ উপাদান (নেগেটিভ ইনডেক্স)
arr = np.array([10, 20, 30, 40, 50])
 

# 2য় থেকে 4র্থ উপাদান (নেগেটিভ ইনডেক্স)
print(arr[-4:-1])  # আউটপুট: [20 30 40]


[20 30 40]


Broadcasting  

 It expands a smaller array to perform operations with a larger array.


In [281]:
arr = np.array([10, 20, 30, 40])
scalar = 5

# Scalar value এর সাথে অ্যারে যোগ করা
print(arr + scalar)   


[15 25 35 45]


In [282]:
arr = np.array([10, 20, 30, 40])
scalar = 10

# Scalar value এর সাথে অ্যারে যোগ করা
print(arr + scalar)   


[20 30 40 50]


In [ ]:
# দুটি ভিন্ন আকারের অ্যারে তৈরি
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([10, 20])

# দুটি ভিন্ন আকারের অ্যারের অপারেশন
print(arr1 + arr2)   


[[11 22]
 [13 24]]


In [358]:
# Array Slicing
import numpy as np

#  select a random item from a list
items = [1, 2, 3, 4, 5]
random_choice = np.random.choice(items)

print(random_choice)


4


In [360]:
 # Array Slicing
import numpy as np
#  select a random item from a list
items = [1, 2, 3, 4, 5]
random_choice = np.random.choice(items)

print(random_choice)


3


In [286]:
x= np.array([1,2,3])


In [362]:
print(x)


[1 2 3]


In [363]:
print(type(x))     # shows the data type of variable x (e.g., numpy.ndarray) .  
print(x.shape)     # shows the dimensions (rows, columns) of x
print(x.dtype)     # shows the data type of elements (e.g., int32, float64)
print(x.ndim)      # shows how many dimensions x has (1D, 2D, etc.)
print(x.size)      # shows total number of elements in x


<class 'numpy.ndarray'>
(3,)
int64
1
3


In [289]:
print(type(x))       # check type of x is numpy array or not

print(x.shape)     # check shape of x   (3,) means  1 dimension and 3 elements
 
print(x.dtype)   # check data type of elements in x

print(x.ndim)    # check number of dimensions

print(x.size)    # check number of elements in x

<class 'numpy.ndarray'>
(3,)
int64
1
3


In [364]:

y= np.array([[1,  2,   3],     
             [4,  5,  6]])


print(y)                # prints the 2D array y

print(y.shape)          # prints the shape of y (rows, columns)

print(y.ndim)           # prints the number of dimensions of y  

print(y.size)           # prints the total number of elements in y

print(y.dtype)          # prints the data type of elements in y

print(type(y))          # prints the type of variable y (e.g., numpy.ndarray)

print(y[0,1])           # Accessing element at first row, second column

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
<class 'numpy.ndarray'>
2


In [291]:
print(type(x))     # shows the data type of variable x (e.g., numpy.ndarray) .  
print(x.shape)     # shows the dimensions (rows, columns) of x
print(x.dtype)     # shows the data type of elements (e.g., int32, float64)
print(x.ndim)      # shows how many dimensions x has (1D, 2D, etc.)
print(x.size)      # shows total number of elements in x


<class 'numpy.ndarray'>
(3,)
int64
1
3


In [366]:
# NumPy  is a powerful library for numerical computing in Python.
 #data analysis all
# mean, median and Standard Deviation
 

import numpy as np  

numbers = [1,2,3,4,5]

meanvalue = np.mean(numbers)

medianvalue = np.median(numbers)

stddeviation = np.std(numbers)

print("Mean:", meanvalue)

print("Median:", medianvalue)

print("Standard Deviation:", stddeviation)

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951


In [293]:

import numpy as np  

numbers = [1,2,3,4,5,6,7,8,9,10]

meanvalue = np.mean(numbers)

medianvalue = np.median(numbers)

stddeviation = np.std(numbers)

print("Mean:", meanvalue)

print("Median:", medianvalue)
print("Standard Deviation:", stddeviation)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143


In [294]:
#  another   :   shortcut way but difficult mone hoy onek  er jonno 
import numpy as np
numbers = [1,2,3,4,5]
print (np.mean(numbers) )
print (np.median(numbers))
print (np.std(numbers))

3.0
3.0
1.4142135623730951


In [295]:

 
# create  a numpy array 


import numpy as np

numbers = [1,2,3,4,5]

np_array = np.array(numbers)  # create numpy array using list

print(np_array)

# print type of the array
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


এখানে যখন অ্যারের টাইপ দেখেছি, আউটপুট পেয়েছি ndarray, যা নামপাই অ্যারের ডেটা টাইপ।

নামপাই ব্যবহার করে র‍্যান্ডম নাম্বার তৈরি

অনেক সময় আমাদের কিছু ডামি ডেটা জেনারেট করতে হয়। নামপাই দিয়ে সহজেই করা যায়। যেমনঃ

In [367]:
# Create an array of 10 zeros
import numpy as np
# creating an array of 10 zeros
zeros = np.zeros(10)
print(zeros)
print(type(zeros))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [368]:
import numpy as np
# creating an array of 10 zeros
zeros = np.zeros(5)
print("Total number of Zeros: ", zeros)
print(type(zeros))

Total number of Zeros:  [0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


## 1 দিয়ে পূর্ণ একটা অ্যারে তৈরিঃ

In [ ]:
# 1 দিয়ে পূর্ণ একটা অ্যারে তৈরিঃ
import numpy as np
ones = np.ones(5)
print(ones)  

print(type(ones)) 

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [369]:
# 1 দিয়ে পূর্ণ একটা অ্যারে তৈরিঃ
import numpy as np
ones = np.ones(10)
print("Total number of Ones: ", ones)  
print(type(ones)) 

Total number of Ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


নির্দিষ্ট রেঞ্জের অ্যারে তৈরিঃ

In [300]:
 
import numpy as np
# creating an array with 1-9 numbers
numbers = np.arange(10)
print("Total Number of Range : ", numbers)


Total Number of Range :  [0 1 2 3 4 5 6 7 8 9]


র‍্যান্ডম অ্যারে তৈরিঃ

In [370]:
 
import numpy as np
# generating random array
rand = np.random.rand(5)
print("Random array: ", rand)
print(type(rand))


Random array:  [0.32434502 0.12208795 0.35629784 0.90682844 0.27213225]
<class 'numpy.ndarray'>


In [371]:
# generating random array 
import numpy as np
 
rand = np.random.rand(3)

print("Random array: ", rand)

print(type(rand))
 
print(rand.dtype)  # check data type of elements in rand        
print(rand.shape)  # check shape of rand        
print(rand.ndim)   # check number of dimensions        
print(rand.size)   # check number of elements in rand           

Random array:  [6.47690121e-01 5.20376995e-04 3.52568856e-01]
<class 'numpy.ndarray'>
float64
(3,)
1
3


In [374]:
 
import numpy as np
# generating random array          value  is different every time
rand = np.random.rand(5)
print("Random array: ", rand)
print(type(rand))

Random array:  [0.40383617 0.06489225 0.25391541 0.24687606 0.69630427]
<class 'numpy.ndarray'>


শূন্য অ্যারে তৈরিঃ

In [375]:
# শূন্য অ্যারে তৈরিঃ

 
import numpy as np
# creating empty array
empty = np.empty(3)
 
print("Empty array: ", empty)


Empty array:  [6.47690121e-01 5.20376995e-04 3.52568856e-01]


In [378]:
import numpy as np
# creating empty array
empty_array = np.empty(10)
print("Empty array: ", empty_array)
print(type(empty_array))    

Empty array:  [4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323 3.0e-323 3.5e-323 4.0e-323
 4.4e-323 4.9e-323]
<class 'numpy.ndarray'>


এই কোডটি NumPy লাইব্রেরি ব্যবহার করে একটি খালি অ্যারে তৈরি করে।
np.empty(10) দ্বারা ১০টি উপাদান বিশিষ্ট একটি অ্যারে তৈরি হয়,
 তবে এতে কোনো মান ইনিশিয়ালাইজ করা হয় না।
ফলে অ্যারেতে মেমরির আগের র‍্যান্ডম বা গারবেজ মানগুলো দেখা যায়।
print("Empty array:", empty_array) লাইনটি অ্যারেটি স্ক্রিনে প্রদর্শন করে।
print(type(empty_array)) লাইনটি অ্যারেটির টাইপ দেখায়, যা <class 'numpy.ndarray'>।
অর্থাৎ এটি একটি NumPy অ্যারে, 
যা দ্রুত অ্যারে তৈরির জন্য ব্যবহৃত হয় কিন্তু মান নির্দিষ্ট করে না।

কাস্টম একটা অ্যারে তৈরিঃ  
 এর মানে 0-100 এর মধ্যে সংখ্যা গুলো ব্যবহার করে একটা অ্যারে তৈরি করতে। যেখানে প্রতি ধাপে ৫টা সংখ্যা বাদ দিয়ে পরের সংখ্যা নিতে। আউটপুট পাবো এমনঃ

In [379]:
import numpy as np
# creating custom array
lst = np.arange(0, 100, 5)
print("Custom array: ", lst)

Custom array:  [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [380]:
import numpy as np
# creating custom array
lst = np.arange(0, 50, 4)
print("Custom array: ", lst)

Custom array:  [ 0  4  8 12 16 20 24 28 32 36 40 44 48]


একটা নির্দিষ্ট নাম্বার ব্যবহার করে অ্যারে ফিল করাঃ

 
এর মানে হচ্ছে ১০টা আইটেমের একটা অ্যারে নিতে যা 4 সংখ্যা দিয়ে পূরণ করবে।  

 

In [381]:
import numpy as np
fours = np.full(10, 4)
print(fours)

[4 4 4 4 4 4 4 4 4 4]


In [382]:
import numpy as np
fours = np.full(5, 2)
print(fours)

[2 2 2 2 2]


একটা নির্দিষ্ট নাম্বার ব্যবহার করে অ্যারে ফিল করাঃ

 
এর মানে হচ্ছে 20 টা আইটেমের একটা অ্যারে নিতে যা 10 সংখ্যা দিয়ে পূরণ করবে।  

 
 

In [383]:
import numpy as np
ten= np.full(20, 10)
print(ten)

[10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10]


In [384]:
# 
import numpy as np
list_numbers= [1,2,3,4,5]
numpy_array_numbers= np.array(list_numbers)
print(numpy_array_numbers)
print(type(numpy_array_numbers))
 


[1 2 3 4 5]
<class 'numpy.ndarray'>


উপরে যে অ্যারে গুলো তৈরি করেছি, সেগুলো ছিল সিঙ্গেল ডাইমেনশন। আমরা চাইলে মাল্টি ডাইমেনশন অ্যারে তৈরি করতে পারিঃ
2D অ্যারে তৈরিঃ
যেমন 2D অ্যারে এভাবে তৈরি করতে পারিঃ

In [310]:
 # create 2D array

import numpy as np
two_d = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]])
 
print(two_d)
print(type(two_d))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [ ]:
 # create 2D array
import numpy as np
two_d = np.array([[1, 2, 3, 4] , [5, 6, 7, 8]])
 
print(two_d)  
print(type(two_d))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [ ]:
 
import numpy as np
two_d = np.array( [   [1, 2, 3, 4]   ,
                      [5, 6, 7, 8]   ] )
  
print(two_d)
print(type(two_d))
print(two_d.shape)
print(two_d.dtype)  
print(two_d.ndim)
print(two_d.size)


[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
(2, 4)
int64
2
8


In [313]:
# arange function
arange= np.arange(1, 20, 2)  # 1 to 20 , step 2 

print(arange)    # prints the array

print(type(arange))  # prints the type of variable arange

print(arange.shape)  # prints the shape of the array

print(arange.dtype)  # prints the data type of elements in the array

print(arange.ndim)  # prints the number of dimensions of the array 

print(arange.size)   # prints the total number of elements in the array

[ 1  3  5  7  9 11 13 15 17 19]
<class 'numpy.ndarray'>
(10,)
int64
1
10


In [385]:
# arange function
arange= np.arange(0, 20, 2)  # 1 to 20 , step 2 

print(arange)    # prints the array

print(type(arange))  # prints the type of variable arange

print(arange.shape)  # prints the shape of the array

print(arange.dtype)  # prints the data type of elements in the array

print(arange.ndim)  # prints the number of dimensions of the array 

print(arange.size)   # prints the total number of elements in the array

[ 0  2  4  6  8 10 12 14 16 18]
<class 'numpy.ndarray'>
(10,)
int64
1
10


In [388]:
# The linspace() function creates 5 equally spaced numbers between 0 and 1.

linspace= np.linspace(0, 1, 5)  # start=0, end=1, num=5 

print(linspace)    # prints the array

print(type(linspace))  # prints the type of variable linspace  

print(linspace.shape)  # prints the shape of the array

print(linspace.dtype)  # prints the data type of elements in the array  

[0.   0.25 0.5  0.75 1.  ]
<class 'numpy.ndarray'>
(5,)
float64


In [315]:
 
import numpy as np
two_d = np.array( [   [1, 2, 3, 4]  
                    ,   [5, 6, 7, 8]   ] )
  
print(two_d)
print(type(two_d))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [316]:
 
import numpy as np
two_d = np.array( [[1, 2, 3, 4] ,
                   [5, 6, 7, 8]] )
   
print(two_d)
print(type(two_d))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


2D র‍্যান্ডম অ্যারে এভাবে তৈরি করতে পারিঃ

যা আমাদের 5*5 একটা র‍্যান্ডম অ্যারে তৈরি করে দিবে। আর আউটপুট দিবে এমনঃ

In [317]:
 
import numpy as np
two_d_random = np.random.rand(5, 5)
print(two_d_random)
print(type(two_d_random))


[[0.17052412 0.06505159 0.94888554 0.96563203 0.80839735]
 [0.30461377 0.09767211 0.68423303 0.44015249 0.12203823]
 [0.49517691 0.03438852 0.9093204  0.25877998 0.66252228]
 [0.31171108 0.52006802 0.54671028 0.18485446 0.96958463]
 [0.77513282 0.93949894 0.89482735 0.59789998 0.92187424]]
<class 'numpy.ndarray'>


In [318]:
 
import numpy as np
two_d_random = np.random.rand(4, 4)
print(two_d_random)
print(type(two_d_random))   

[[0.0884925  0.19598286 0.04522729 0.32533033]
 [0.38867729 0.27134903 0.82873751 0.35675333]
 [0.28093451 0.54269608 0.14092422 0.80219698]
 [0.07455064 0.98688694 0.77224477 0.19871568]]
<class 'numpy.ndarray'>


In [389]:
 
import numpy as np
two_d_random = np.random.rand(2, 2)
print(two_d_random)
print(type(two_d_random))   

[[0.71227059 0.14808693]
 [0.99774049 0.26678101]]
<class 'numpy.ndarray'>


In [320]:
 
import numpy as np
two_d_random = np.random.rand(2, 4)
print(two_d_random)
print(type(two_d_random))

[[0.77127035 0.07404465 0.35846573 0.11586906]
 [0.86310343 0.62329813 0.33089802 0.06355835]]
<class 'numpy.ndarray'>


In [321]:
# Create a 3x3 array filled with the value 7
import numpy as np
 
numpy_array = np.full((3, 3), 7) # create 3x3 array filled with 7
 
print( numpy_array) 
print(type(numpy_array))

[[7 7 7]
 [7 7 7]
 [7 7 7]]
<class 'numpy.ndarray'>


# NumPy Array Slicing :

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [322]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) 

[2 3 4 5]


In [323]:
# NumPy Array Slicing :
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:]) 

[5 6 7]


In [324]:
# NumPy Array Slicing :
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4]) 

[1 2 3 4]


# Negative Slicing

In [325]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])    # -3 theke  suru   but -1 er age porjonto 

[5 6]


Use the step value to determine the step of the slicing:

In [326]:
# NumPy Array Slicing :
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])  # start=1, stop=5, step=2        step 2 mean  ekta skip kore nibe   index= value 1 theke suru kore 5 er age porjonto 2 step kore nibe, so  start value 2, then skip 3, then 4   so output hobe 2,4

[2 4]


In [327]:
# NumPy Array Slicing :
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])  

print(arr[::2]) # start index 0  ,   end value  steps of 2

[1 3 5 7]


Slicing 2-D Arrays

In [328]:
# NumPy Array Slicing :
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print(arr[1, 1:4])  # Accessing elements from 2nd row, columns 2 to 4

[7 8 9]


In [329]:
#
import numpy as np

arr = np.array( [[1,  2,  3,  4,  5],            # 0 row
                [6,   7,  8,  9,  10]])           # 1 row

print(arr[0:2, 2])   # 0:2   range 0 theke 2  orthat   0 ,1   karon     0 theke 2  ar   maje .    2  column porjonto jabe 

[3 8]


# explain

print(arr[0:2, 2])
→ Uses slicing to access specific elements.

0:2 → means both the first and second rows.

2 → means the third column (since indexing starts at 0).

 

From row 0 → value 3

From row 1 → value 8

Checking the Data Type of an Array

The NumPy array object has a property called dtype that returns the data type of the array:

In [330]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [331]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype) 

<U6


<U6 means a Unicode string of up to 6 characters (the longest word is “banana”).

In [332]:
import numpy as np
 
numpy_array = np.full((2, 2), 5)
 
print( numpy_array)
print(type(numpy_array))

[[5 5]
 [5 5]]
<class 'numpy.ndarray'>


In [333]:
import numpy as np
 
numpy_array = np.full((2, 1), 5)
 
print( numpy_array)
print(type(numpy_array))

[[5]
 [5]]
<class 'numpy.ndarray'>


In [334]:
import numpy as np
 
numpy_array = np.full((3, 2), 5)
 
print( numpy_array)
print(type(numpy_array))

[[5 5]
 [5 5]
 [5 5]]
<class 'numpy.ndarray'>


In [335]:
import numpy as np
 
numpy_array = np.full((1 , 2), 5)
 
print( numpy_array)
print(type(numpy_array))    

[[5 5]]
<class 'numpy.ndarray'>


Example 1: np.zeros()
 np.zeros((2,3)) 
একটি 2 সারি ও 3 কলামের array তৈরি করে, যেখানে সব মান 0।

In [336]:
# Create a 2x3 array of zeros
import numpy as np
zeros_array = np.zeros((2, 3))
print("Zeros array:\n", zeros_array)
print(type(zeros_array))


Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [337]:
# Create a 2x3 array of zeros
import numpy as np
zeros_array = np.zeros((2, 3))
print("Zeros array:", zeros_array)
print(type(zeros_array))    


Zeros array: [[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


Example 2: np.ones()    .


np.ones((3,2)) একটি 3 সারি ও 2 কলামের array তৈরি করে, যেখানে সব মান 1।

In [338]:
# Create a 3x2 array of ones
import numpy as np
ones_array = np.ones((3, 2))
print("Ones array:\n", ones_array)
print(type(ones_array))

Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>


Example 3: np.arange() .


np.arange(5, 15, 2) মানে হলো 5 থেকে শুরু করে 15-এর আগে পর্যন্ত সংখ্যা তৈরি করা, প্রতি ধাপে 2 করে বাড়বে।

In [339]:
import numpy as np
range_array = np.arange(5, 15, 2)
print("Arange array:", range_array)
print(type(range_array))


Arange array: [ 5  7  9 11 13]
<class 'numpy.ndarray'>


Bonus Example: np.full()   


np.full((2,3),7) একটি 2x3 ম্যাট্রিক্স তৈরি করে, যার সব ঘরেই মান 7।

In [340]:
import numpy as np
full_array = np.full((2, 3), 7)
print("Full array:\n", full_array)
print(type(full_array))


Full array:
 [[7 7 7]
 [7 7 7]]
<class 'numpy.ndarray'>


In [341]:
# create 3x3 identity matrix
identity_matrix = np.identity(3)
print( identity_matrix)
print(type(identity_matrix)) 
print(identity_matrix.shape) 
print(identity_matrix.dtype)    
    

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
<class 'numpy.ndarray'>
(3, 3)
float64


In [342]:
# create 2x2 identity matrix
identity_matrix = np.identity(2)
print( identity_matrix)
print(type(identity_matrix)) 
print(identity_matrix.shape) 
print(identity_matrix.dtype)    
    

[[1. 0.]
 [0. 1.]]
<class 'numpy.ndarray'>
(2, 2)
float64


In [343]:
identity_matrix = np.identity(3 ,dtype=int )
print( identity_matrix)
print(type(identity_matrix)) 
print(identity_matrix.shape) 
print(identity_matrix.dtype)    
    

[[1 0 0]
 [0 1 0]
 [0 0 1]]
<class 'numpy.ndarray'>
(3, 3)
int64


3D অ্যারেকে ভাবতে পারেন একের অধিক 2D অ্যারের সমষ্টি। যেমনঃ

 

In [344]:
 
import numpy as np
 
three_d = np.array([  [[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12] ],
 
                   [[13, 14, 15, 16],
                    [17, 18, 19, 20],
                    [21, 22, 23, 24]]  ])
 
print(three_d)                   # prints the 3D array three_d

print(type(three_d))             # prints the type of variable three_d (e.g., numpy.ndarray)

print(three_d.shape)             # prints the shape of three_d (depth, rows, columns)

print(three_d.dtype)             # prints the data type of elements in three_d

print(three_d.ndim)            # prints the number of dimensions of three_d

print(three_d.size)            # prints the total number of elements in three_d



[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
<class 'numpy.ndarray'>
(2, 3, 4)
int64
3
24


এখানে দুইটা 3*4 অ্যারে রয়েছে। 
বুঝতে আরেকটু সহজ হবে যদি আমরা এই অ্যারেটি জেনারেট করিঃ

In [345]:

 
import numpy as np                  # create a 3D array of zeros
 
three_d = np.zeros((2, 3, 4))       # 2 blocks, 3 rows, 4 columns
 
print(three_d)                     # prints the 3D array three_d                        

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


প্রথম অ্যারেটাই আমরা 0 দিয়ে তৈরি করেছি। যদি (2, 3, 4) এর পরিবর্তে (4, 3, 4) লিখি, তাহলেঃ

মানে হচ্ছে 4টা 3*4 অ্যারে।
 যখন এমন মাল্টি ডাইমেনশন অ্যারে নিয়ে কাজ করব,
  তখন উল্টা থেকে পড়ব। যেমন (2, 3, 4) কে পড়ব প্রতিটা রোতে ৪টা আইটেম রয়েছে। 
  চারটা আইটেম করে ৩টা কলাম রয়েছে প্রতি স্লাইচে। এবং স্লাইচ রয়েছে ২টা।

In [346]:
import numpy as np                # create a 3D array of zeros
 
three_d = np.zeros((4, 3, 4))     # 4 blocks, 3 rows, 4 columns
 
print(three_d)                   # prints the 3D array three_d

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


আমার মত রো এবং কলাম কোনটা, ভুলে গেলে আবার স্মরণ করে নিন। প্রথমে রো, পরে কলাম, পরে স্লাইস। তাহলে (4, 3, 4) এর ক্ষেত্রে হবে প্রতি রোতে ৪টা আইটেম করে মোট ৩টা রো রয়েছে, আর স্লাইস রয়েছে ৪টা! আবার অ্যারেতে কত গুলো আইটেম রয়েছে টোটাল তা এই (4, 3, 4) সংখ্যা গুলো গুণ করলেই পাওয়া যাবে। অর্থাৎ (4, 3, 4) সাইজের অ্যারেতে 48টা আইটেম থাকবে।

এবার একটা 3D অ্যারে র‍্যান্ডম নাম্বার দিয়ে তৈরি করিঃ
 
 

In [347]:
 
import numpy as np           # create a 3D array with random values
 
three_d = np.random.rand(2, 4, 4)    # 2 blocks, 4 rows, 4 columns
 
print(three_d)                # prints the 3D array three_d

[[[0.31098232 0.32518332 0.72960618 0.63755747]
  [0.88721274 0.47221493 0.11959425 0.71324479]
  [0.76078505 0.5612772  0.77096718 0.4937956 ]
  [0.52273283 0.42754102 0.02541913 0.10789143]]

 [[0.03142919 0.63641041 0.31435598 0.50857069]
  [0.90756647 0.24929223 0.41038292 0.75555114]
  [0.22879817 0.07697991 0.28975145 0.16122129]
  [0.92969765 0.80812038 0.63340376 0.87146059]]]


একই অ্যারে যদি আমরা একটা নির্দিষ্ট সংখ্যা দিয়ে ফিল করতে চাই, তাহলে এভাবে লিখবঃ

  একটা 2*4*4 অ্যারে তৈরি করবে যা ফিল করবে 6 দিয়ে।

In [348]:
 
import numpy as np        # create a 3D array filled with a specific value
three_d = np.full((2, 4, 4), 6)   # 2 blocks, 4 rows, 4 columns
print(three_d)                  # prints the 3D array three_d

[[[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]]


In [349]:
 
import numpy as np        # create a 3D array filled with a specific value
three_d = np.full((1, 4, 4), 6)   # 2 blocks, 4 rows, 4 columns
print(three_d)                  # prints the 3D array three_d

[[[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]]


In [350]:
 
import numpy as np        # create a 3D array filled with a specific value
three_d = np.full((2, 3, 3), 6)   # 2 blocks, 4 rows, 4 columns
print(three_d)                  # prints the 3D array three_d

[[[6 6 6]
  [6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]
  [6 6 6]]]


In [351]:
 
import numpy as np                     # create a 3D array filled with a specific value
three_d = np.full((2, 3, 3), 10)        # 2 blocks, 4 rows, 4 columns
print(three_d)                         # prints the 3D array three_d 

[[[10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]]]
